### PR TITLE
form validation, creating new contacts and deploeyed, i hope

### PR DESCRIPTION
**Pull request by waamber**

### CODE REVIEW

**Comment by rousell** [comment]
@waamber your CRD functionality appears to be working well! It looks like the only thing that you have left to implement for this part is to implement the functionality where the options on the nav bar changes when the user is authenticated, and that the user is able to logout of the application successfully.
amber-no-logout
Let us know when you've completed that last part!

**Comment by waamber** [comment]
okay, I had to force commit it because I'm working on part4 on a different branch, but I think it should all be working with the logout

**Comment by waamber** [comment]
just kidding. i'm having problems pushing up changes on this branch bc i have another open.

**Comment by zoeames** [comment]
👍

**Comment by zoeames** [comment]
since you have another branch open be careful with this merge.  i would suggest you pull down master.  switch to your part4 branch.  merge master into part4 and then push back up

**Pull request merged**
